# Travel数据分析

### 1.导入pandas包

In [1]:
import pandas as pd

### 2.读取文件

In [2]:
data=pd.read_csv("travel2.csv")
data

,地点,短评,出发时间,天数,人均费用,人物,玩法,浏览量
0,婺源,春天的婺源，油菜花开，宛如一幅诗情画意的水墨画,/2020/04/01,5,3000,三五好友,第一次 美食,9055
1,阿联酋,阿联酋｜小狮妹和父母的新年迪拜之旅,/2019/12/10,8,-,-,-,3860
2,AguadePau,来自《一个女生的古巴独行记》（11日自由行攻略）,/2019/09/27,11,20000,独自一人,深度游 美食 摄影 国庆,261
3,建水,云南│我什么也没忘，但有些事只适合收藏,/2019/10/10,8,4000,三五好友,穷游 摄影 古镇 赏秋 国庆,6176
4,日本,日本｜东京の72小时,/2019/09/21,8,-,-,-,1.2万
...,...,...,...,...,...,...,...,...
1994,三亚,【海南】教你如何花最少的钱，玩转不一样的海南,/2019/04/21,4,2500,情侣,短途周末 穷游 摄影 美食 蜜月 五一,4.4万
1995,重庆,#2019五一出游#【重庆】一个人，一背包，一相机从你的全世界路过,/2019/05/01,4,1200,独自一人,短途周末 摄影 美食,2.1万
1996,安庆,自驾安庆，探寻北纬30°线上大别山腹地的奥秘,/2019/05/05,4,2500,-,-,8.3万
1997,衡山,南岳衡山二日游实用攻略,/2019/05/05,2,600,家庭,徒步 五一,8.7万
1998,临沂,【好客山东】山东之美不止是青烟威，还有鲁南的沂蒙仙山,/2019/05/05,3,3000,三五好友,深度游 踏春,7270

### 3.处理人均费用数值

由于爬取时,有些用户无人均费用属性，因此所赋值为"-".因此将所有人均费用的"-"替换成'0'

In [3]:
data['人均费用'].replace('-','0',inplace=True)
data

,地点,短评,出发时间,天数,人均费用,人物,玩法,浏览量
0,婺源,春天的婺源，油菜花开，宛如一幅诗情画意的水墨画,/2020/04/01,5,3000,三五好友,第一次 美食,9055
1,阿联酋,阿联酋｜小狮妹和父母的新年迪拜之旅,/2019/12/10,8,0,-,-,3860
2,AguadePau,来自《一个女生的古巴独行记》（11日自由行攻略）,/2019/09/27,11,20000,独自一人,深度游 美食 摄影 国庆,261
3,建水,云南│我什么也没忘，但有些事只适合收藏,/2019/10/10,8,4000,三五好友,穷游 摄影 古镇 赏秋 国庆,6176
4,日本,日本｜东京の72小时,/2019/09/21,8,0,-,-,1.2万
...,...,...,...,...,...,...,...,...
1994,三亚,【海南】教你如何花最少的钱，玩转不一样的海南,/2019/04/21,4,2500,情侣,短途周末 穷游 摄影 美食 蜜月 五一,4.4万
1995,重庆,#2019五一出游#【重庆】一个人，一背包，一相机从你的全世界路过,/2019/05/01,4,1200,独自一人,短途周末 摄影 美食,2.1万
1996,安庆,自驾安庆，探寻北纬30°线上大别山腹地的奥秘,/2019/05/05,4,2500,-,-,8.3万
1997,衡山,南岳衡山二日游实用攻略,/2019/05/05,2,600,家庭,徒步 五一,8.7万
1998,临沂,【好客山东】山东之美不止是青烟威，还有鲁南的沂蒙仙山,/2019/05/05,3,3000,三五好友,深度游 踏春,7270

### 4.展示数据信息

从输出信息所知,一共有1999条数据，每条数据有8个属性值.后面出示每条属性值的基本信息，如非空为多少

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999 entries, 0 to 1998
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   地点      1999 non-null   object
 1   短评      1999 non-null   object
 2   出发时间    1999 non-null   object
 3   天数      1999 non-null   object
 4   人均费用    1999 non-null   object
 5   人物      1999 non-null   object
 6   玩法      1999 non-null   object
 7   浏览量     1999 non-null   object
dtypes: object(8)
memory usage: 125.1+ KB

### 5.去除错误数据

In [5]:
data=data[~data['地点'].isin(['攻略'])]
data=data[~data['天数'].isin(['99+'])]
data

,地点,短评,出发时间,天数,人均费用,人物,玩法,浏览量
0,婺源,春天的婺源，油菜花开，宛如一幅诗情画意的水墨画,/2020/04/01,5,3000,三五好友,第一次 美食,9055
1,阿联酋,阿联酋｜小狮妹和父母的新年迪拜之旅,/2019/12/10,8,0,-,-,3860
2,AguadePau,来自《一个女生的古巴独行记》（11日自由行攻略）,/2019/09/27,11,20000,独自一人,深度游 美食 摄影 国庆,261
3,建水,云南│我什么也没忘，但有些事只适合收藏,/2019/10/10,8,4000,三五好友,穷游 摄影 古镇 赏秋 国庆,6176
4,日本,日本｜东京の72小时,/2019/09/21,8,0,-,-,1.2万
...,...,...,...,...,...,...,...,...
1994,三亚,【海南】教你如何花最少的钱，玩转不一样的海南,/2019/04/21,4,2500,情侣,短途周末 穷游 摄影 美食 蜜月 五一,4.4万
1995,重庆,#2019五一出游#【重庆】一个人，一背包，一相机从你的全世界路过,/2019/05/01,4,1200,独自一人,短途周末 摄影 美食,2.1万
1996,安庆,自驾安庆，探寻北纬30°线上大别山腹地的奥秘,/2019/05/05,4,2500,-,-,8.3万
1997,衡山,南岳衡山二日游实用攻略,/2019/05/05,2,600,家庭,徒步 五一,8.7万
1998,临沂,【好客山东】山东之美不止是青烟威，还有鲁南的沂蒙仙山,/2019/05/05,3,3000,三五好友,深度游 踏春,7270

### 6.转换数据类型

In [6]:
data['天数']=data['天数'].astype(int)
data['人均费用']=data['人均费用'].astype(int)

In [7]:
data=data[data['人均费用']>200]
data=data[data['天数']<=15]

### 7.筛选数据

In [8]:
data=data.reset_index(drop=True)
data

,地点,短评,出发时间,天数,人均费用,人物,玩法,浏览量
0,婺源,春天的婺源，油菜花开，宛如一幅诗情画意的水墨画,/2020/04/01,5,3000,三五好友,第一次 美食,9055
1,AguadePau,来自《一个女生的古巴独行记》（11日自由行攻略）,/2019/09/27,11,20000,独自一人,深度游 美食 摄影 国庆,261
2,建水,云南│我什么也没忘，但有些事只适合收藏,/2019/10/10,8,4000,三五好友,穷游 摄影 古镇 赏秋 国庆,6176
3,海宁,海洪宁静，盐潮入官，百里钱塘，春暖花开--驾“浙”观大潮访金庸、赏樱花睡房车,/2020/03/23,2,900,情侣,自驾 赏樱 踏春 清明,2.2万
4,敦煌,甘青│到远方去，到那个山野苍茫的远方，熟悉的地方没有景色,/2019/05/10,10,3500,三五好友,环游 毕业游 穷游,1.4万
...,...,...,...,...,...,...,...,...
1509,三亚,【海南】教你如何花最少的钱，玩转不一样的海南,/2019/04/21,4,2500,情侣,短途周末 穷游 摄影 美食 蜜月 五一,4.4万
1510,重庆,#2019五一出游#【重庆】一个人，一背包，一相机从你的全世界路过,/2019/05/01,4,1200,独自一人,短途周末 摄影 美食,2.1万
1511,安庆,自驾安庆，探寻北纬30°线上大别山腹地的奥秘,/2019/05/05,4,2500,-,-,8.3万
1512,衡山,南岳衡山二日游实用攻略,/2019/05/05,2,600,家庭,徒步 五一,8.7万
1513,临沂,【好客山东】山东之美不止是青烟威，还有鲁南的沂蒙仙山,/2019/05/05,3,3000,三五好友,深度游 踏春,7270

### 8.处理月份

In [9]:
def Month(e):
    
    m=str(e).split('/')[2]
    
    if m=='01':
        return '一月'
    if m=='02':
        return '二月'
    if m=='03':
        return '三月'
    if m=='04':
        return '四月'
    if m=='05':
        return '五月'
    if m=='06':
        return '六月'
    if m=='07':
        return '七月'
    if m=='08':
        return '八月'
    if m=='09':
        return '九月'
    if m=='10':
        return '十月'
    if m=='11':
        return '十一月'
    if m=='12':
        return '十二月'

In [10]:
data['旅行月份']=data['出发时间'].apply(Month)
data['出发时间']=pd.to_datetime(data['出发时间'])
data

,地点,短评,出发时间,天数,人均费用,人物,玩法,浏览量,旅行月份
0,婺源,春天的婺源，油菜花开，宛如一幅诗情画意的水墨画,2020-04-01,5,3000,三五好友,第一次 美食,9055,四月
1,AguadePau,来自《一个女生的古巴独行记》（11日自由行攻略）,2019-09-27,11,20000,独自一人,深度游 美食 摄影 国庆,261,九月
2,建水,云南│我什么也没忘，但有些事只适合收藏,2019-10-10,8,4000,三五好友,穷游 摄影 古镇 赏秋 国庆,6176,十月
3,海宁,海洪宁静，盐潮入官，百里钱塘，春暖花开--驾“浙”观大潮访金庸、赏樱花睡房车,2020-03-23,2,900,情侣,自驾 赏樱 踏春 清明,2.2万,三月
4,敦煌,甘青│到远方去，到那个山野苍茫的远方，熟悉的地方没有景色,2019-05-10,10,3500,三五好友,环游 毕业游 穷游,1.4万,五月
...,...,...,...,...,...,...,...,...,...
1509,三亚,【海南】教你如何花最少的钱，玩转不一样的海南,2019-04-21,4,2500,情侣,短途周末 穷游 摄影 美食 蜜月 五一,4.4万,四月
1510,重庆,#2019五一出游#【重庆】一个人，一背包，一相机从你的全世界路过,2019-05-01,4,1200,独自一人,短途周末 摄影 美食,2.1万,五月
1511,安庆,自驾安庆，探寻北纬30°线上大别山腹地的奥秘,2019-05-05,4,2500,-,-,8.3万,五月
1512,衡山,南岳衡山二日游实用攻略,2019-05-05,2,600,家庭,徒步 五一,8.7万,五月
1513,临沂,【好客山东】山东之美不止是青烟威，还有鲁南的沂蒙仙山,2019-05-05,3,3000,三五好友,深度游 踏春,7270,五月

### 9.处理浏览量

In [11]:
import re

def Look(e):
    
    if '万' in e:
        num=re.findall('(.*?)万',e)
        return float(num[0])*10000
    else:
        return float(e)

In [12]:
data['浏览次数']=data['浏览量'].apply(Look)
data.drop(['浏览量'],axis=1,inplace=True)
data['浏览次数']=data['浏览次数'].astype(int)
data.head()

,地点,短评,出发时间,天数,人均费用,人物,玩法,旅行月份,浏览次数
0,婺源,春天的婺源，油菜花开，宛如一幅诗情画意的水墨画,2020-04-01,5,3000,三五好友,第一次 美食,四月,9055
1,AguadePau,来自《一个女生的古巴独行记》（11日自由行攻略）,2019-09-27,11,20000,独自一人,深度游 美食 摄影 国庆,九月,261
2,建水,云南│我什么也没忘，但有些事只适合收藏,2019-10-10,8,4000,三五好友,穷游 摄影 古镇 赏秋 国庆,十月,6176
3,海宁,海洪宁静，盐潮入官，百里钱塘，春暖花开--驾“浙”观大潮访金庸、赏樱花睡房车,2020-03-23,2,900,情侣,自驾 赏樱 踏春 清明,三月,22000
4,敦煌,甘青│到远方去，到那个山野苍茫的远方，熟悉的地方没有景色,2019-05-10,10,3500,三五好友,环游 毕业游 穷游,五月,14000

### 10.前十旅游地点

In [13]:
data1=data
data1['地点'].value_counts().head(10)

三亚      136
成都       78
重庆       31
厦门       31
北京       29
丽江       28
曼谷       28
平遥       21
西安       20
呼伦贝尔     19
Name: 地点, dtype: int64

### 11.Top10旅游地点的人均费用

In [14]:
loc=data1['地点'].value_counts().head(10).index.tolist()
print(loc)
loc_data=data1[data1['地点'].isin(loc)]
price_mean=round(loc_data['人均费用'].groupby(loc_data['地点']).mean(),1)
print(price_mean)
price_mean2=[1630.1,1862.9,1697.9,1743.4,1482.4,1586.4,1897.0,1267.5,1973.8,1723.7]

['三亚', '成都', '重庆', '厦门', '北京', '丽江', '曼谷', '平遥', '西安', '呼伦贝尔']
地点
三亚      4072.6
丽江      4023.0
北京      3689.2
厦门      2318.9
呼伦贝尔    4778.9
平遥      1390.5
成都      2718.6
曼谷      5257.5
西安      3038.0
重庆      2675.2
Name: 人均费用, dtype: float64

In [15]:
price_mean.index.tolist()

['三亚', '丽江', '北京', '厦门', '呼伦贝尔', '平遥', '成都', '曼谷', '西安', '重庆']

In [16]:
price_mean.values.tolist()

[4072.6,
 4023.0,
 3689.2,
 2318.9,
 4778.9,
 1390.5,
 2718.6,
 5257.5,
 3038.0,
 2675.2]

### 12.绘制费用图 Bar

In [17]:
from pyecharts.charts import Bar

In [18]:

bar=(
    Bar()
    .add_xaxis(price_mean.index.tolist())
    .add_yaxis('目的地Top10人均费用',price_mean.values.tolist())
    .render('费用.html')
    
)

In [19]:
data1['天数'].value_counts()

3     273
5     212
4     194
7     146
6     143
8     105
2      89
9      81
10     75
1      51
12     36
11     36
15     32
14     24
13     17
Name: 天数, dtype: int64

In [20]:
data1['旅行时长']=data1['天数'].apply(lambda x:str(x)+'天')

In [21]:
data1

,地点,短评,出发时间,天数,人均费用,人物,玩法,旅行月份,浏览次数,旅行时长
0,婺源,春天的婺源，油菜花开，宛如一幅诗情画意的水墨画,2020-04-01,5,3000,三五好友,第一次 美食,四月,9055,5天
1,AguadePau,来自《一个女生的古巴独行记》（11日自由行攻略）,2019-09-27,11,20000,独自一人,深度游 美食 摄影 国庆,九月,261,11天
2,建水,云南│我什么也没忘，但有些事只适合收藏,2019-10-10,8,4000,三五好友,穷游 摄影 古镇 赏秋 国庆,十月,6176,8天
3,海宁,海洪宁静，盐潮入官，百里钱塘，春暖花开--驾“浙”观大潮访金庸、赏樱花睡房车,2020-03-23,2,900,情侣,自驾 赏樱 踏春 清明,三月,22000,2天
4,敦煌,甘青│到远方去，到那个山野苍茫的远方，熟悉的地方没有景色,2019-05-10,10,3500,三五好友,环游 毕业游 穷游,五月,14000,10天
...,...,...,...,...,...,...,...,...,...,...
1509,三亚,【海南】教你如何花最少的钱，玩转不一样的海南,2019-04-21,4,2500,情侣,短途周末 穷游 摄影 美食 蜜月 五一,四月,44000,4天
1510,重庆,#2019五一出游#【重庆】一个人，一背包，一相机从你的全世界路过,2019-05-01,4,1200,独自一人,短途周末 摄影 美食,五月,21000,4天
1511,安庆,自驾安庆，探寻北纬30°线上大别山腹地的奥秘,2019-05-05,4,2500,-,-,五月,83000,4天
1512,衡山,南岳衡山二日游实用攻略,2019-05-05,2,600,家庭,徒步 五一,五月,87000,2天
1513,临沂,【好客山东】山东之美不止是青烟威，还有鲁南的沂蒙仙山,2019-05-05,3,3000,三五好友,深度游 踏春,五月,7270,3天

In [22]:
data1['人物'].value_counts()

三五好友    550
家庭      224
情侣      216
独自一人    152
亲子      128
-       115
闺蜜      115
学生       14
Name: 人物, dtype: int64

In [23]:
m = data1['浏览次数'].sort_values(ascending=False).index[:].tolist()

In [24]:
data1 = data1.loc[m]
data1 = data1.reset_index(drop = True)
data1

,地点,短评,出发时间,天数,人均费用,人物,玩法,旅行月份,浏览次数,旅行时长
0,海参崴,【蓝白光年】贝加尔湖手机摄影纪行,2019-01-24,7,6400,情侣,深度游 美食 摄影 寒假,一月,924000,7天
1,大连,2019暑假大连亲子6日游,2019-07-21,9,2300,家庭,第一次 暑假,七月,865000,9天
2,广州,想打死同伴的广州三日游,2019-08-13,3,2680,三五好友,第一次 美食,八月,828000,3天
3,下川岛,下川岛的美景，是你想象不到的美。,2019-05-06,2,600,家庭,短途周末 美食 摄影 春节 国庆,五月,797000,2天
4,北京,一家老小向前冲6天5晚北京每天3万步暴走游,2019-07-14,6,5000,家庭,第一次 暑假,七月,767000,6天
...,...,...,...,...,...,...,...,...,...,...
1509,稻城,川西八日游,2019-10-18,11,7000,闺蜜,徒步,十月,101,11天
1510,澳门,【点赞澳门】这才是澳门正确的打开方式！,2019-03-08,3,2300,闺蜜,深度游 短途周末 美食 踏春,三月,85,3天
1511,烟台,错开高峰去烟台，感受只有我的旅行世界,2019-11-08,7,5000,独自一人,第一次 摄影 探险 赏秋,十一月,59,7天
1512,拉萨,西藏8日游,2019-06-14,10,7000,情侣,第一次 端午,六月,56,10天
1513,曼谷,🇹🇭泰国旅行写真拍照攻略&游记📷,2019-10-12,4,5000,闺蜜,摄影 国庆,十月,36,4天

In [25]:
data1['旅行月份'].value_counts()

六月     193
九月     184
七月     178
十月     164
八月     158
五月     148
十二月    133
十一月    125
一月     111
四月      55
三月      34
二月      31
Name: 旅行月份, dtype: int64

### 12.词云分析

In [26]:
word_list = []
for i in data1['玩法']:
    s = re.split('\xa0',i)
    word_list.append(s)  
dict = {}
for j in range(len(word_list)):
    for i in word_list[j]:
        if i not in dict:
            dict[i] = 1
        else:
            dict[i]+=1
#print(dict)
list = []
for item in dict.items():
    list.append(item)
for i in range(1,len(list)):
    for j in range(0,len(list)-1):
        if list[j][1]<list[j+1][1]:
            list[j],list[j+1] = list[j+1],list[j]
print(list)

[('深度游', 470), ('摄影', 455), ('美食', 427), ('第一次', 342), ('自驾', 301), ('夏季', 247), ('暑假', 242), ('短途周末', 218), ('海滨海岛', 183), ('国庆', 146), ('冬季', 140), ('-', 116), ('穷游', 108), ('古镇', 107), ('赏秋', 100), ('徒步', 64), ('端午', 63), ('环游', 63), ('春节', 58), ('五一', 55), ('中秋节', 49), ('寒假', 47), ('潜水', 46), ('购物', 45), ('跨年', 39), ('踏春', 38), ('蜜月', 37), ('探险', 36), ('人文', 35), ('圣诞', 28), ('漫游', 28), ('温泉', 27), ('毕业游', 26), ('滑雪', 18), ('清明', 17), ('赏枫', 14), ('骑行', 12), ('婚纱', 10), ('游轮', 10), ('万圣节', 6), ('赏樱', 4)]

In [27]:
m1 = data1['人物'].value_counts().index.tolist()
n1 = data1['人物'].value_counts().values.tolist()

In [28]:
from pyecharts import options as opts
from pyecharts.charts import Pie

In [29]:
p=(
    Pie()
    .add('',[z for z in zip(m1,n1)])
    .set_colors(['blue','green','yellow','red','pink','orange','purple','black'])
    .set_global_opts(title_opts=opts.TitleOpts(title='Top出游方式'))
    .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}:{c}"))
    .render('出游方式.html')
)

In [30]:
from pyecharts.charts import Line

In [31]:
m3 = data1['出发时间'].value_counts().sort_index()[:]
m4 = m3['2019'].index
n4 = m3['2019'].values

In [32]:
m3['2019'].sort_values().tail(10)

2019-05-11    11
2019-11-02    11
2019-08-01    11
2019-07-24    12
2019-07-05    12
2019-09-20    13
2019-06-07    15
2019-06-01    17
2019-05-01    23
2019-10-01    23
Name: 出发时间, dtype: int64

In [33]:
l=(
    Line()
    .add_xaxis(m3['2019'].index.tolist())
    .add_yaxis('出游时间',m3['2019'].values.tolist())
    .render('出游时间.html')
)

In [34]:
m5 = []
n5 = []
for i in range(20):
    m5.append(list[i][0])
    n5.append(list[i][1])
m5.reverse()
m6 = m5
n5.reverse()
n6 = n5

In [35]:
b=(
    Bar()
    .add_xaxis(m6)
    .add_yaxis('出游玩法',n6)
    .set_global_opts(title_opts=opts.TitleOpts(title='Top出游玩法'))
    .render('出游玩法.html')
)

In [36]:
data_mo = data1[((data1['旅行月份'] =='七月')|(data1['旅行月份'] =='八月'))&(data1['人物']=='三五好友')].drop(['旅行时长'],axis = 1)
data_mo.head(10)

,地点,短评,出发时间,天数,人均费用,人物,玩法,旅行月份,浏览次数
2,广州,想打死同伴的广州三日游,2019-08-13,3,2680,三五好友,第一次 美食,八月,828000
43,重庆,导航都怕的山城，迷失在重庆的大街小巷里,2019-08-05,4,4000,三五好友,第一次,八月,130000
46,成都,遇见，成都—那些与美食相关的小美好，这里你都可以找到（4天3夜小众玩法）,2019-08-08,4,1000,三五好友,短途周末 美食 摄影 夏季,八月,126000
59,成都,孤独患者寻味记,2019-08-01,5,1000,三五好友,美食 暑假,八月,117000
67,普吉岛,普吉岛跟团游是一种什么体验？多图航拍视角跟大家讲解。,2019-07-26,5,2999,三五好友,第一次 潜水 夏季,七月,109000
69,银川,自驾游宁夏，六天五晚的大西北探秘之旅,2019-08-06,6,5000,三五好友,深度游 自驾 探险,八月,107000
72,永嘉,诗画浙江，山水秉承，与你漫步在悠悠楠溪江,2019-07-27,3,1500,三五好友,深度游 短途周末 摄影 夏季,七月,106000
73,成都,"不一样的成都,不一样的美食,探寻天府之国,寻遍江湖美味",2019-08-30,4,1500,三五好友,美食,八月,105000
95,塞尔维亚，被遗落的巴尔干明珠，硝烟散尽的小众秘境,塞尔维亚，被遗落的巴尔干明珠，硝烟散尽的小众秘境,2019-07-14,5,6000,三五好友,深度游 夏季,七月,92000
99,2019自驾千里草原风景大道，第16次终于圆梦穿越锡林郭勒盟全境,2019自驾千里草原风景大道，第16次终于圆梦穿越锡林郭勒盟全境,2019-07-16,10,4200,三五好友,深度游 自驾 摄影 夏季,七月,91000

In [37]:
data_mo2 = data1[((data1['人物'] =='情侣')|(data1['人物'] =='独自一人'))&(data1['旅行月份']=='十月')].drop(['旅行时长'],axis = 1)
data_mo2.head(10)

,地点,短评,出发时间,天数,人均费用,人物,玩法,旅行月份,浏览次数
35,兴城,兴城游记,2018-10-16,2,300,独自一人,古镇,十月,143000
352,三清山,2019年国庆：江西上饶+婺源+三清山,2019-10-08,5,5000,情侣,国庆,十月,42000
393,三亚,【行摄三亚】情侣带你玩转三亚五大海湾，免费旅拍地大揭密,2019-10-19,6,5000,情侣,自驾 国庆,十月,38000
403,大连,在世界最宜居城市，来一场穿越时空的深度旅行,2019-10-24,7,10000,独自一人,深度游 自驾 徒步 国庆 冬季,十月,37000
408,阿尔山,2018年10月底呼伦贝尔租车自驾5天，深秋，阿尔山满洲里,2018-10-23,5,2300,情侣,深度游 自驾 穷游 国庆 冬季,十月,37000
413,敦煌,3000公里自驾，陪爱人去西北看最美秋季「星空，胡杨，雅丹，沙漠一次看个够」,2019-10-21,9,7500,情侣,深度游 自驾 摄影,十月,36000
417,文成,旅游浙江最美小城，风景秀丽还是名人故里,2019-10-29,4,2000,情侣,短途周末 美食 摄影,十月,36000
450,塞维利亚,【神雕侠旅】西班牙浪漫之旅，2000公里12城，深度自驾全攻略,2019-10-26,13,15000,情侣,深度游 自驾 摄影 赏秋,十月,33000
509,三亚,小夫妻旅行录丨辞职去旅行，三亚是我们新生活的第一站！,2019-10-13,3,2000,情侣,深度游 自驾,十月,29000
515,珀斯,【AOTUMAN】孤独之城相依之旅·西澳珀斯11日自驾之旅,2018-10-02,11,14000,情侣,自驾 摄影 蜜月 国庆,十月,29000

In [38]:
import jieba
import jieba.analyse
import re

In [39]:
punc = '~`!#$%^&*()_+-=|\';":/.,?><~·！@#￥%……&*（）——+-=“：’；、。，？》《{}【】'
def remove_fuhao(e):
    short = re.sub(r"[%s]+" % punc, " ", e)
    return short
def cut_word(text):
    text = jieba.cut_for_search(str(text))
    return ' '.join(text)

In [40]:
data2=data1

In [41]:
data2['简介'] = data2['短评'].apply(remove_fuhao).apply(cut_word)
data2.head()

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\lenovo\AppData\Local\Temp\jieba.cache
Loading model cost 1.173 seconds.
Prefix dict has been built successfully.

,地点,短评,出发时间,天数,人均费用,人物,玩法,旅行月份,浏览次数,旅行时长,简介
0,海参崴,【蓝白光年】贝加尔湖手机摄影纪行,2019-01-24,7,6400,情侣,深度游 美食 摄影 寒假,一月,924000,7天,蓝 白光 年 贝加尔 贝加尔湖 手机 摄影 纪行
1,大连,2019暑假大连亲子6日游,2019-07-21,9,2300,家庭,第一次 暑假,七月,865000,9天,暑假 大连 亲子 日游
2,广州,想打死同伴的广州三日游,2019-08-13,3,2680,三五好友,第一次 美食,八月,828000,3天,想 打死 同伴 的 广州 三日 游
3,下川岛,下川岛的美景，是你想象不到的美。,2019-05-06,2,600,家庭,短途周末 美食 摄影 春节 国庆,五月,797000,2天,下 川岛 的 美景 是 你 想象 不到 的 美
4,北京,一家老小向前冲6天5晚北京每天3万步暴走游,2019-07-14,6,5000,家庭,第一次 暑假,七月,767000,6天,一家 老小 一家老小 向前 冲 天 晚 北京 每天 万步 暴走 游

In [42]:
word = data2['简介'].values.tolist()
fb = open(r'.\travel_text.txt','w',encoding='utf-8')
for i in range(len(word)):
    fb.write(word[i])
with open(r'.\travel_text.txt','r',encoding='utf-8')as f:
    words = f.read()
    f.close

In [43]:
jieba.analyse.set_stop_words(r'./cn_stopwords.txt')
new_words = jieba.analyse.textrank(words, topK=30, withWeight=True)
print(new_words)

[('攻略', 1.0), ('三亚', 0.8553001044113387), ('自驾', 0.7308670168713672), ('旅行', 0.6720845702975154), ('美食', 0.5682018595897484), ('成都', 0.4789737663829506), ('游记', 0.3454894817922448), ('亲子', 0.30427951509066226), ('打卡', 0.27901352367540155), ('全攻', 0.2701793549872677), ('厦门', 0.24066064709546575), ('景点', 0.22356721499299098), ('全攻略', 0.2199179037897284), ('遇见', 0.20942510754906135), ('时光', 0.20669139326246233), ('度假', 0.1903950343717827), ('古城', 0.18906194688986946), ('美景', 0.18662654824325173), ('泰国', 0.18657910981905512), ('旅游', 0.18343191332320843), ('重庆', 0.17576432804328612), ('玩转', 0.17177680754599078), ('网红', 0.15999014532744657), ('体验', 0.1579181310291953), ('邂逅', 0.15652456504774742), ('西北', 0.15594542324585522), ('北京', 0.1456950488064779), ('西安', 0.14565476293179108), ('世界', 0.14371924497787905), ('新疆', 0.13996229919811878)]

In [44]:
from pyecharts.charts import WordCloud

In [45]:
word1 = []
num1 = []
for i in range(len(new_words)):    
    
    word1.append(new_words[i][0])
    num1.append(new_words[i][1])

In [46]:
c=(
    WordCloud()
    .add("词云分析",new_words)
    .set_global_opts(title_opts=opts.TitleOpts(title="WordCloud-图片"))
    .render('词云.html')
)

In [47]:
m7 = data1['旅行时长'].value_counts().index.tolist()
n7 = data1['旅行时长'].value_counts().values.tolist()

In [48]:
m7.reverse()
m8 = m7
n7.reverse()
n8 = n7

In [49]:
bar=(
    Bar()
    .add_xaxis(m8)
    .add_yaxis('旅行时长',n8)
    .set_global_opts(title_opts=opts.TitleOpts(title="Top-旅行时长"))
    .render('旅行时长.html')
)

In [50]:
data4 = data1.drop(['旅行时长','简介'],axis = 1)
data4

,地点,短评,出发时间,天数,人均费用,人物,玩法,旅行月份,浏览次数
0,海参崴,【蓝白光年】贝加尔湖手机摄影纪行,2019-01-24,7,6400,情侣,深度游 美食 摄影 寒假,一月,924000
1,大连,2019暑假大连亲子6日游,2019-07-21,9,2300,家庭,第一次 暑假,七月,865000
2,广州,想打死同伴的广州三日游,2019-08-13,3,2680,三五好友,第一次 美食,八月,828000
3,下川岛,下川岛的美景，是你想象不到的美。,2019-05-06,2,600,家庭,短途周末 美食 摄影 春节 国庆,五月,797000
4,北京,一家老小向前冲6天5晚北京每天3万步暴走游,2019-07-14,6,5000,家庭,第一次 暑假,七月,767000
...,...,...,...,...,...,...,...,...,...
1509,稻城,川西八日游,2019-10-18,11,7000,闺蜜,徒步,十月,101
1510,澳门,【点赞澳门】这才是澳门正确的打开方式！,2019-03-08,3,2300,闺蜜,深度游 短途周末 美食 踏春,三月,85
1511,烟台,错开高峰去烟台，感受只有我的旅行世界,2019-11-08,7,5000,独自一人,第一次 摄影 探险 赏秋,十一月,59
1512,拉萨,西藏8日游,2019-06-14,10,7000,情侣,第一次 端午,六月,56
1513,曼谷,🇹🇭泰国旅行写真拍照攻略&游记📷,2019-10-12,4,5000,闺蜜,摄影 国庆,十月,36

In [55]:
k_list = []
the_list = []
keyword = input('请输入旅行月份：')
data5 = data4[data4['旅行月份'] == str(keyword)]
keyword1 = input('请输入结伴出游方式：')
data6 = data5[data5['人物'] == str(keyword1)]
price = int(input('请输入预期价格上限：'))
data7 = data6[data6['人均费用']<=price]
day1 = int(input('请输入旅行时长下限：'))
day2 = int(input('请输入旅行时长上限：'))
data8 = data7[(data7['天数']>=day1)&(data7['天数']<=day2)]
data8

请输入旅行月份： 八月
请输入结伴出游方式： 三五好友
请输入预期价格上限： 2000
请输入旅行时长下限： 3
请输入旅行时长上限： 10

,地点,短评,出发时间,天数,人均费用,人物,玩法,旅行月份,浏览次数
46,成都,遇见，成都—那些与美食相关的小美好，这里你都可以找到（4天3夜小众玩法）,2019-08-08,4,1000,三五好友,短途周末 美食 摄影 夏季,八月,126000
59,成都,孤独患者寻味记,2019-08-01,5,1000,三五好友,美食 暑假,八月,117000
73,成都,"不一样的成都,不一样的美食,探寻天府之国,寻遍江湖美味",2019-08-30,4,1500,三五好友,美食,八月,105000
107,阳朔,八月，桂林阳朔3日休闲游，一场歌舞唱响八桂大地,2019-08-14,3,2000,三五好友,深度游 夏季,八月,88000
113,阿坝,探秘遗落人间的仙境，与阿坝的不期而遇！,2019-08-08,3,2000,三五好友,深度游 中秋节 国庆,八月,86000
435,三门,行至水穷处坐看云起时——2019“三门湾至味”发现体验之旅,2019-08-21,3,2000,三五好友,徒步 美食 摄影 暑假,八月,34000
442,连云港,二访大美之境—连云港花果山,2019-08-24,3,2000,三五好友,深度游 短途周末 摄影 暑假,八月,34000
499,楠溪江,逃离高温酷暑，来楠溪江过个清凉夏日，寻瀑布乘竹筏看美景,2019-08-03,3,1000,三五好友,第一次 自驾 夏季 暑假,八月,30000
598,银川,收下这份宁夏玩乐地图（固原+中卫+银川）,2019-08-01,7,2000,三五好友,美食 暑假,八月,23000
834,日照,带你看我眼中的日照，看花、赏竹、游泳、航拍，这样玩才最嗨！,2019-08-06,3,500,三五好友,深度游 短途周末 自驾 暑假 中秋节,八月,10000